/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TitleSettings = string;
/**
 * Navigation to perform on title click. Example: If you are at route /my/route/asset then 'settings/profile' routes to '/my/route/settings/profile'.
 */
export type TitleNavigation = string;
/**
 * Whether to add a leading slash to the navigation route.
 */
export type AddLeadingSlash = boolean;
/**
 * Whether to add a trailing slash to the navigation route.
 */
export type AddTraillingSlash = boolean;
export type FontSize = number;
export type FontWeight = number;
export type Label = string;
/**
 * Name of the icon from https://fonts.google.com/icons
 */
export type IconName = string;
/**
 * Navigation to perform on click. Example: If you are at route /my/route/asset then 'settings/profile' routes to '/my/route/settings/profile'.
 */
export type NavigationRoute = string;
/**
 * Whether to add a leading slash to the navigation route.
 */
export type AddLeadingSlash1 = boolean;
/**
 * Whether to add a trailing slash to the navigation route.
 */
export type AddTraillingSlash1 = boolean;
export type NavigationItems = {
    label?: Label;
    iconName?: IconName;
    route?: NavigationRoute;
    leadingSlash?: AddLeadingSlash1;
    trailingSlash?: AddTraillingSlash1;
    [k: string]: unknown;
}[];

export interface InputData {
    title?: TitleSettings;
    route?: TitleNavigation;
    leadingSlash?: AddLeadingSlash;
    trailingSlash?: AddTraillingSlash;
    style?: ItemStyle;
    navItems?: NavigationItems;
    [k: string]: unknown;
}
export interface ItemStyle {
    fontSize?: FontSize;
    fontWeight?: FontWeight;
    color?: FontColor;
    backgroundColor?: BackgroundColor;
    [k: string]: unknown;
}
export interface FontColor {
    [k: string]: unknown;
}
export interface BackgroundColor {
    [k: string]: unknown;
}
